### ISSUE TITLE
Create a complete verification framework in github

### ISSUE THREAD

**Issue by erizhang** [Icay12/the-Game-of-Life#3]
As we know, this project uses `cpputest` as unit test framework, but if a contributor clone your source code to locally, he/she cannot execute the unit test compiling since lack library. Here you need to do below works to make it happen:
1. Add [`cpputest` github repository](https://github.com/cpputest/cpputest.git) as this project's submodule;
2. Create [travis](https://travis-ci.org/) CI job and deploy in this project
3. Update readme to make the travis CI job feedback visible.

Have fun :o)

**Comment by Icay12** [comment]
the issue has been fixed in commit de0042902ba07d522ab5dfce4aea68a770e3bae9
